spring:
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8080

app:
  kafka:
    topic:
      cfo: org_cdc_polka_test.public.ucfo
      werk: org_cdc_polka_test.public.uwerks